### ISSUE TITLE
Unnecessary system libraries 

### ISSUE THREAD

**Issue by steve4444** [donaldsonjw/bigloo#3]
In Windows, despite compiling  with `-static-all-bigloo`, to run a hello-world executable I am still required to ship with it:

    libgmp-10.dll
    libiconv-2.dll
    libpcre-1.dll
    libunistring-2.dll
  
Is this the expected behaviour?
Is it possible to remove them from the executable dependencies?

**Comment by donaldsonjw** [comment]
For --static-all-bigloo to work in the manner you want, you will need static versions of libgmp, libiconv, libpcre and libunistring and link against them instead of the dynamic versions.

By the way, I am not actively working on the Win64 port of Bigloo, so you should not expect this repository to be updated to newer versions of bigloo.
